# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: publysher/hugo

pages:
  script:
  - apt-get install wget
  - wget https://github.com/gohugoio/hugo/releases/download/v0.24.1/hugo_0.24.1_Linux-64bit.deb
  - dpkg -i hugo_0.24.1_Linux-64bit.deb
  - rm hugo_0.24.1_Linux-64bit.deb
  - cd exampleSite
  - git clone .. themes/BluestNight
  - hugo -b https://shadow53.gitlab.io/BluestNight/
  - mv public ..
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - hugo
  except:
  - master
