# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: publysher/hugo

pages:
  script:
  - cd exampleSite
  - git clone .. themes/BluestNight
  - hugo -b https://shadow53.gitlab.io/BluestNight/
  - mv public ..
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - hugo
  except:
  - master
