[params]

[params.color]
    page_background = "#000000"
    main_background = "#050505"
    alt_background = "#252525"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
    accent = "#2c8cef"
    accent_text = "#e2e2e2"

[params.fonts]
    header_style = "sans-serif"
    body_style = "sans-serif"
    print_header_style = "sans-serif"
    print_body_style = "serif"

[params.sidebar]
    [params.sidebar.patreon]
        path = "widgets/patreon.html"
        cache = true
    [params.sidebar.search]
        path = "widgets/search.html"
        cache = true
    [params.sidebar.recent]
        path = "widgets/recent.html"
    [params.sidebar.events]
        path = "widgets/events.html"
        cache = true
    [params.sidebar.categories]
        path = "widgets/categories.html"
        cache = true
    [params.sidebar.taglist]
        path = "widgets/taglist.html"
        cache = true

[mediaTypes]
    [mediaTypes."netlify/headers"]
        suffix = ""

[outputFormats]
    [outputFormats.NetlifyHeaders]
        isPlainText = true
        basename = "_headers"
        mediaType = "netlify/headers"
        notAlternative = true
