name = "BluestNight"
license = "MIT"
licenselink = "https://dev.shadow53.com/source/BluestNight/browse/master/LICENSE.md"
description = "A featureful, configurable, yet sleek dark theme for Hugo."
homepage = "https://bluestnight.com/"
tags = [
    "Blog",
    "Clean",
    "Creative",
    "Contact Form",
    "Custom Colors",
    "Dark",
    "Error Validation",
    "Extensible",
    "Flexbox",
    "Font Awesome",
    "Mobile Friendly",
    "Netlify",
    "Print CSS",
    "Responsive",
    "Syntax Highlighting",
    "Search",
    "Widgets",
    "Writing"
]
min_version = 0.40.3

[author]
  name = "Michael Bryant"
  homepage = "https://shadow53.com"
